-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgG9DaAFWVucgXUHT/
0eAFjknE1y7PJ+Ngyf7bJuY70Z2gCgYIKoZIzj0DAQehRANCAASHkZ9QUPteNroR
y3yhurq0HT7lZScyDoBKBfc8IfiDOoPwr47uU8CCOcT2Y4pvzEBIZ6BHXzLJUCMU
vVlWpjfA
-----END PRIVATE KEY-----